# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os, configparser

Config = configparser.ConfigParser()
Config.read(".\\Settings.ini")

THREADS = Config["PERFORMANCE"].getint("THREADS", os.cpu_count())
HOME_FOLDER = Config["OTHER"].get("HOME_FOLDER", os.path.dirname(os.path.realpath(__file__)).replace("\\", "/"))
SAVE_FOLDER = Config["OTHER"].get("SAVE_FOLDER", os.path.dirname(os.path.realpath(__file__)).replace("\\", "/"))
LANGUAGE = Config["OTHER"].get("LANGUAGE", "EN")
if LANGUAGE == "EN":
    LANGUAGE = 0
elif LANGUAGE == "UA":
    LANGUAGE = 1

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 260)
        Form.setStyleSheet("color:rgb(180, 180, 180);\n"
"background-color: rgb(50, 50, 50);\n"
"font: 14pt \"Tahoma\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Vid.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 400, 70))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(170, 35, 220, 20))
        self.horizontalSlider.setStyleSheet("font: 12pt \"Tahoma\";")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(os.cpu_count())
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksAbove)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setValue(int(THREADS))
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 35, 130, 20))
        self.label.setStyleSheet("font: 12pt \"Tahoma\";")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 400, 131))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 35, 90, 20))
        self.label_2.setStyleSheet("font: 12pt \"Tahoma\";")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(170, 30, 150, 25))
        self.comboBox.setStyleSheet("font: 12pt \"Tahoma\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setCurrentIndex(LANGUAGE)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 140, 20))
        self.label_3.setStyleSheet("font: 12pt \"Tahoma\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 150, 20))
        self.label_4.setStyleSheet("font: 12pt \"Tahoma\";")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(8, 55, 384, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(170, 68, 200, 22))
        self.lineEdit.setStyleSheet("font: 10pt \"Tahoma\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText(HOME_FOLDER)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton.setGeometry(QtCore.QRect(372, 68, 22, 22))
        self.toolButton.setObjectName("toolButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 98, 200, 22))
        self.lineEdit_2.setStyleSheet("font: 10pt \"Tahoma\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setText(SAVE_FOLDER)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_2.setGeometry(QtCore.QRect(372, 98, 22, 22))
        self.toolButton_2.setObjectName("toolButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 230, 80, 24))
        self.pushButton.setStyleSheet("font: 12pt \"Tahoma\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 230, 130, 24))
        self.pushButton_2.setStyleSheet("font: 12pt \"Tahoma\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 230, 80, 24))
        self.pushButton_3.setStyleSheet("font: 12pt \"Tahoma\";")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def UpdateValues(self):
        Config = configparser.ConfigParser()
        Config.read(".\\Settings.ini")

        THREADS = Config["PERFORMANCE"].getint("THREADS", os.cpu_count())
        HOME_FOLDER = Config["OTHER"].get("HOME_FOLDER", os.path.dirname(os.path.realpath(__file__)).replace("\\", "/"))
        SAVE_FOLDER = Config["OTHER"].get("SAVE_FOLDER", os.path.dirname(os.path.realpath(__file__)).replace("\\", "/"))
        LANGUAGE = Config["OTHER"].get("LANGUAGE", "EN")
        if LANGUAGE == "EN":
            LANGUAGE = 0
        elif LANGUAGE == "UA":
            LANGUAGE = 1

        self.horizontalSlider.setValue(int(THREADS))
        self.lineEdit.setText(HOME_FOLDER)
        self.lineEdit_2.setText(SAVE_FOLDER)
        self.comboBox.setCurrentIndex(LANGUAGE)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Settings"))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("Form", "Performance"))
        self.label.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Count of CPUs used for conversion</p></body></html>"))
        self.label.setText(QtCore.QCoreApplication.translate("Form", "CPU count"))
        self.groupBox_2.setTitle(QtCore.QCoreApplication.translate("Form", "Other"))
        self.label_2.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Language of programm </p></body></html>"))
        self.label_2.setText(QtCore.QCoreApplication.translate("Form", "Language"))
        self.comboBox.setItemText(0, QtCore.QCoreApplication.translate("Form", "English"))
        self.comboBox.setItemText(1, QtCore.QCoreApplication.translate("Form", "Ukrainian"))
        self.label_3.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Default path of videos </p></body></html>"))
        self.label_3.setText(QtCore.QCoreApplication.translate("Form", "Input Video Folder"))
        self.label_4.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Default path to save converted video</p></body></html>"))
        self.label_4.setText(QtCore.QCoreApplication.translate("Form", "Output Video Folder"))
        self.toolButton.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Browse</p></body></html>"))
        self.toolButton.setText(QtCore.QCoreApplication.translate("Form", "..."))
        self.toolButton_2.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Browse</span></p></body></html>"))
        self.toolButton_2.setText(QtCore.QCoreApplication.translate("Form", "..."))
        self.pushButton.setText(QtCore.QCoreApplication.translate("Form", "Cancel"))
        self.pushButton_2.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Apply changes</p></body></html>"))
        self.pushButton_2.setText(QtCore.QCoreApplication.translate("Form", "Apply"))
        self.pushButton_3.setText(QtCore.QCoreApplication.translate("Form", "Ok"))
